### ISSUE TITLE
RSA Key to ansible vault

### ISSUE THREAD

**Issue by Lebowski89** [mother-of-all-self-hosting/ansible-role-authelia#1]
-

**Comment by spantaleev** [comment]
This question is not related to mash-playbook, nor to this role itself. The way you do it is like with any other Ansible playbook.

Nevertheless, I will give you some pointers below.

-------------------

In `vars.yml`:

```yml
authelia_config_identity_providers_oidc_issuer_private_key: "{{ vault_authelia_config_identity_providers_oidc_issuer_private_key }}"
```

You then create `vault.yml` using `ansible-vault create path/to/vault.yml` with content like this:

```yml
vault_authelia_config_identity_providers_oidc_issuer_private_key: |
  key
  content
  here
```

You can do further edits to the `vault.yml` file using `ansible-vault edit ..`. See the documentation for `ansible-vault` for more details.

It should be noted that there are other ways to use vault-encrypted secrets as well. You may also have them inline, directly in the `vars.yml` file. I find it cleaner to use a dedicated `vault.yml` file next to my `vars.yml` file though.

-----

Later on, when invoking the playbook, you will need to pass a `--ask-vault-pass` argument.

If you'd rather not pass `--ask-vault-pass` and type a password each time, you may also set the `ANSIBLE_VAULT_PASSWORD_FILE` environment variable with a value pointing to a file which contains your vault password. This also makes `ansible-vault` commands not ask for a password.

**Comment by Lebowski89** [comment]
I was talking about inline the entire time, but yeah. No worries.
